name: run from the py file 
on: push

jobs:
    Hello:
        runs-on: ubundu-latest

        steps:
            - name: clone repo
              uses: actions/checkout@v3

            - name: setup python 
              uses: action/setup-python@v4
              with:
                python-version: "3.10"

            - name: run a python script
              run: python hello.py
      