name: cronjob
on:
  schedule:
    - cron: '* * * * *'

jobs:
  cron_job:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: setup the python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: run the python script
        run: python cron.py

