name: for Unit test 

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: clone code
        uses: actions/checkout@v3

      - name: Set up the Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tests
        run: python -m unittest test_square_number
  